name: Snykscan
on:
  push

jobs:
  SNyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SnykScanning
      run: |
         echo "----------Download Latest Snyk CLI-----------"
         curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1297.1/snyk-linux"
         chmod +x snyk
         ls -lrt
         echo "----------Authenticating Snyk-----------"
         ./snyk auth ${{secrets.snyk_token}}
         echo "----------Snyk Scanning-----------"
         ./snyk monitor --all-projects -d
         
         
         
             
                     
